# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TrackingHome' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for TrackingHome
  pod 'Moya', '~> 14.0'
  pod 'R.swift'
  pod 'RealmSwift'
  
  pod 'AWSMobileClient', '~> 2.12.2'
  pod 'amplify-tools'
  pod 'Amplify'
  pod 'AWSPluginsCore'
  pod 'AmplifyPlugins/AWSAPIPlugin'
  pod 'PhoneNumberKit', '~> 3.1'
  pod 'AwsUserPoolSignIn'
  
  target 'TrackingHomeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
